### ISSUE TITLE
Test failures with Ruby 2.5

### ISSUE THREAD

**Issue by graaff** [rspec/rspec-expectations#1031]
With ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux] I'm seeing the following test failures with the released version 3.7.0:

```
  1) RSpec::Expectations::FailureAggregator when used via `aggregate_failures` when an expectation failure happens in another thread propagates it as-is if there are no other failures or errors
     Failure/Error: raise "Warnings were generated: #{output}" if has_output?
     
     RuntimeError:
       Warnings were generated: #<Thread:0x000055844ad47aa0@/var/tmp/portage/dev-ruby/rspec-expectations-3.7.0/work/ruby25/rspec-expectations-3.7.0/spec/rspec/expectations/failure_aggregator_spec.rb:237 run> terminated with exception (report_on_exception is true):
       /usr/lib64/ruby/gems/2.5.0/gems/rspec-support-3.7.0/lib/rspec/support.rb:97:in `block in <module:Support>': expected `2.odd?` to return true, got false (RSpec::Expectations::ExpectationNotMetError)
       	from /usr/lib64/ruby/gems/2.5.0/gems/rspec-support-3.7.0/lib/rspec/support.rb:106:in `notify_failure'
       	from /var/tmp/portage/dev-ruby/rspec-expectations-3.7.0/work/ruby25/rspec-expectations-3.7.0/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
       	from /var/tmp/portage/dev-ruby/rspec-expectations-3.7.0/work/ruby25/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:40:in `handle_failure'
       	from /var/tmp/portage/dev-ruby/rspec-expectations-3.7.0/work/ruby25/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
       	from /var/tmp/portage/dev-ruby/rspec-expectations-3.7.0/work/ruby25/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
       	from /var/tmp/portage/dev-ruby/rspec-expectations-3.7.0/work/ruby25/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
       	from /var/tmp/portage/dev-ruby/rspec-expectations-3.7.0/work/ruby25/rspec-expectations-3.7.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
       	from /var/tmp/portage/dev-ruby/rspec-expectations-3.7.0/work/ruby25/rspec-expectations-3.7.0/spec/rspec/expectations/failure_aggregator_spec.rb:237:in `block (6 levels) in <module:Expectations>'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-support-3.7.0/lib/rspec/support/spec/stderr_splitter.rb:54:in `verify_no_warnings!'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-support-3.7.0/lib/rspec/support/spec.rb:25:in `block (2 levels) in <top (required)>'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:357:in `run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:509:in `block in run_owned_hooks_for'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:508:in `each'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:508:in `run_owned_hooks_for'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:595:in `block in run_example_hooks_for'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:594:in `each'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:594:in `run_example_hooks_for'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:465:in `run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:507:in `run_after_example'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:273:in `block in run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:466:in `block in run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:604:in `run_around_example_hooks_for'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:466:in `run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:251:in `run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:628:in `block in run_examples'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:624:in `map'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:624:in `run_examples'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:590:in `run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:591:in `block in run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:591:in `map'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:591:in `run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:118:in `map'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1896:in `with_suite_hooks'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/reporter.rb:79:in `report'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:112:in `run_specs'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:87:in `run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:71:in `run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/bin/rspec:4:in `<top (required)>'
     # /usr/bin/rspec-3:9:in `load'
     # /usr/bin/rspec-3:9:in `<main>'
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

  2) RSpec::Expectations::FailureAggregator when used via `aggregate_failures` when an expectation failure happens in another thread includes the failure in the failures array if there are other failures
     Failure/Error: raise "Warnings were generated: #{output}" if has_output?
     
     RuntimeError:
       Warnings were generated: #<Thread:0x000055844ad39108@/var/tmp/portage/dev-ruby/rspec-expectations-3.7.0/work/ruby25/rspec-expectations-3.7.0/spec/rspec/expectations/failure_aggregator_spec.rb:223 run> terminated with exception (report_on_exception is true):
       /usr/lib64/ruby/gems/2.5.0/gems/rspec-support-3.7.0/lib/rspec/support.rb:97:in `block in <module:Support>': expected `2.odd?` to return true, got false (RSpec::Expectations::ExpectationNotMetError)
       	from /usr/lib64/ruby/gems/2.5.0/gems/rspec-support-3.7.0/lib/rspec/support.rb:106:in `notify_failure'
       	from /var/tmp/portage/dev-ruby/rspec-expectations-3.7.0/work/ruby25/rspec-expectations-3.7.0/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
       	from /var/tmp/portage/dev-ruby/rspec-expectations-3.7.0/work/ruby25/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:40:in `handle_failure'
       	from /var/tmp/portage/dev-ruby/rspec-expectations-3.7.0/work/ruby25/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
       	from /var/tmp/portage/dev-ruby/rspec-expectations-3.7.0/work/ruby25/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
       	from /var/tmp/portage/dev-ruby/rspec-expectations-3.7.0/work/ruby25/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
       	from /var/tmp/portage/dev-ruby/rspec-expectations-3.7.0/work/ruby25/rspec-expectations-3.7.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
       	from /var/tmp/portage/dev-ruby/rspec-expectations-3.7.0/work/ruby25/rspec-expectations-3.7.0/spec/rspec/expectations/failure_aggregator_spec.rb:223:in `block (6 levels) in <module:Expectations>'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-support-3.7.0/lib/rspec/support/spec/stderr_splitter.rb:54:in `verify_no_warnings!'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-support-3.7.0/lib/rspec/support/spec.rb:25:in `block (2 levels) in <top (required)>'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:357:in `run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:509:in `block in run_owned_hooks_for'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:508:in `each'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:508:in `run_owned_hooks_for'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:595:in `block in run_example_hooks_for'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:594:in `each'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:594:in `run_example_hooks_for'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:465:in `run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:507:in `run_after_example'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:273:in `block in run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:466:in `block in run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:604:in `run_around_example_hooks_for'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:466:in `run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:251:in `run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:628:in `block in run_examples'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:624:in `map'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:624:in `run_examples'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:590:in `run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:591:in `block in run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:591:in `map'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:591:in `run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:118:in `map'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1896:in `with_suite_hooks'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/reporter.rb:79:in `report'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:112:in `run_specs'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:87:in `run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:71:in `run'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /usr/lib64/ruby/gems/2.5.0/gems/rspec-core-3.7.0/bin/rspec:4:in `<top (required)>'
     # /usr/bin/rspec-3:9:in `load'
     # /usr/bin/rspec-3:9:in `<main>'
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
```
