### ISSUE TITLE
If == matcher fails with empty Diff, error notice should be more helpful.

### ISSUE THREAD

**Issue by tvdeyen** [rspec/rspec-expectations#123]
Comparing two objects via == that are not equal, but have no differences make rspec fail. The error notice shown is:

``` shell
Diff:
```

It would be helpful if an explanation of what's the problem shows up. Like the comparing with eq notice!

**Comment by AdrienBD** [comment]
Sorry to reopen this issue but I am facing the empty diff message again...
This time I am not comparing rails Object but their json : 
```
RSpec::Mocks::MockExpectationError: ElasticSearchUtils received :index_stat with unexpected arguments
  expected: (:download, {"action"=>"download", "active"=>true, "created_at"=>Sat, 05 Sep 2015 10:04:59 CEST +02:00, "device_id"=>nil, "mobile_application_id"=>189, "mobile_application_update_id"=>292, "store_id"=>932, "updated_at"=>Mon, 07 Sep 2015 10:04:59 CEST +02:00, "user_id"=>663, "version"=>1, "id"=>"55ed452b4d42507f6e000000"})
       got: (:download, {"action"=>"download", "active"=>true, "created_at"=>Sat, 05 Sep 2015 10:04:59 CEST +02:00, "device_id"=>nil, "mobile_application_id"=>189, "mobile_application_update_id"=>292, "store_id"=>932, "updated_at"=>Mon, 07 Sep 2015 10:04:59 CEST +02:00, "user_id"=>663, "version"=>1, "id"=>"55ed452b4d42507f6e000000"})
Diff:
```

I even checked that the created_at and updated_at times where identical to the millisecond.
Could anyone help me on that ?
