### ISSUE TITLE
Referencing an outer context named subject from a nested context refers to the current subject

### ISSUE THREAD

**Issue by alxberardi** [rspec/rspec-expectations#215]
Please consider the following spec:

``` ruby
require 'rspec'
require 'ostruct'

describe 'an open struct' do
  context 'when instantiated' do
    subject(:an_open_struct) { OpenStruct.new(value: 1) }
    its(:value) { should == 1 }

    context 'when comparing' do
      subject(:another_open_struct) { OpenStruct.new(value: 2) }
      its(:value) { should > an_open_struct.value }
    end
  end
end
```

While with RSpec 2.12.0 it produces 0 failures, with RSpec 2.13.0 it produces the following failure:

```
Failures:

  1) an open struct when instantiated when comparing value 
     Failure/Error: its(:value) { should > an_open_struct.value }
       expected: > 2
            got:   2
```
