### ISSUE TITLE
Improved `change` and `satisfy` failure messages not working

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-expectations#989]
``` ruby
RSpec.describe do
  example "`change` matcher" do
    a = b = 1

    expect {
      a += 1
      b += 2
    }.to change { a }.by(1).and change { b }.by(1)
  end

  example "`satisfy` matcher with symbol to_proc" do
    expect(2).to satisfy(&:odd?).and satisfy(&:positive?)
  end

  example "`satisfy` matcher with explicit blocks" do
    expect(2).to satisfy { |x| x.odd? }.and satisfy { |x| x.positive? }
  end
end
```

The recent changes to improve these failure messages are not working correctly.  Here's the output:

```
Failures:

  1) `satisfy` matcher with explicit blocks
     Failure/Error: expect(2).to satisfy { |x| x.odd? }.and satisfy { |x| x.positive? }
       expected 2 to satisfy block
     # /Users/myron/code/rspec-dev/repos/rspec-support/lib/rspec/support.rb:87:in `block in <module:Support>'
     # /Users/myron/code/rspec-dev/repos/rspec-support/lib/rspec/support.rb:96:in `notify_failure'
     # ./lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # ./lib/rspec/expectations/handler.rb:40:in `handle_failure'
     # ./lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # ./lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # ./lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # ./lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/foo_spec.rb:16:in `block (2 levels) in <top (required)>'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:254:in `instance_exec'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:254:in `block in run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:464:in `block in run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:464:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:251:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:627:in `block in run_examples'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:623:in `map'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:623:in `run_examples'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:589:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:118:in `map'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb:1898:in `with_suite_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/reporter.rb:79:in `report'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:112:in `run_specs'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:87:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:71:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/myron/code/rspec-dev/repos/rspec-core/exe/rspec:4:in `<top (required)>'
     # ./bin/rspec:14:in `load'
     # ./bin/rspec:14:in `<main>'

  2) `satisfy` matcher with symbol to_proc
     Failure/Error: expect(2).to satisfy(&:odd?).and satisfy(&:positive?)

     NoMethodError:
       undefined method `first' for nil:NilClass
     # ./lib/rspec/expectations/block_snippet_extractor.rb:55:in `file_path'
     # ./lib/rspec/expectations/block_snippet_extractor.rb:45:in `source'
     # ./lib/rspec/expectations/block_snippet_extractor.rb:40:in `block_token_extractor'
     # ./lib/rspec/expectations/block_snippet_extractor.rb:36:in `raw_body_snippet'
     # ./lib/rspec/expectations/block_snippet_extractor.rb:32:in `raw_body_lines'
     # ./lib/rspec/expectations/block_snippet_extractor.rb:26:in `body_content_lines'
     # ./lib/rspec/expectations/block_snippet_extractor.rb:10:in `try_extracting_single_line_body_of'
     # ./lib/rspec/matchers/built_in/satisfy.rb:50:in `extract_block_snippet'
     # ./lib/rspec/matchers/built_in/satisfy.rb:41:in `block_representation'
     # ./lib/rspec/matchers/built_in/satisfy.rb:22:in `description'
     # ./lib/rspec/matchers/built_in/satisfy.rb:28:in `failure_message'
     # ./lib/rspec/matchers/built_in/compound.rb:231:in `failure_message'
     # ./lib/rspec/expectations/handler.rb:35:in `handle_failure'
     # ./lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # ./lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # ./lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # ./lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/foo_spec.rb:12:in `block (2 levels) in <top (required)>'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:254:in `instance_exec'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:254:in `block in run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:464:in `block in run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:464:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:251:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:627:in `block in run_examples'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:623:in `map'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:623:in `run_examples'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:589:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:118:in `map'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb:1898:in `with_suite_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/reporter.rb:79:in `report'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:112:in `run_specs'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:87:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:71:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/myron/code/rspec-dev/repos/rspec-core/exe/rspec:4:in `<top (required)>'
     # ./bin/rspec:14:in `load'
     # ./bin/rspec:14:in `<main>'

  3) `change` matcher
     Failure/Error:
       expect {
         a += 1
         b += 2
       }.to change { a }.by(1).and change { b }.by(1)

       expected result to have changed by 1, but was changed by 2
     # /Users/myron/code/rspec-dev/repos/rspec-support/lib/rspec/support.rb:87:in `block in <module:Support>'
     # /Users/myron/code/rspec-dev/repos/rspec-support/lib/rspec/support.rb:96:in `notify_failure'
     # ./lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # ./lib/rspec/expectations/handler.rb:40:in `handle_failure'
     # ./lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # ./lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # ./lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # ./lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./lib/rspec/expectations/expectation_target.rb:101:in `to'
     # ./spec/foo_spec.rb:5:in `block (2 levels) in <top (required)>'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:254:in `instance_exec'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:254:in `block in run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:464:in `block in run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/hooks.rb:464:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example.rb:251:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:627:in `block in run_examples'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:623:in `map'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:623:in `run_examples'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/example_group.rb:589:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:118:in `map'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb:1898:in `with_suite_hooks'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/reporter.rb:79:in `report'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:112:in `run_specs'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:87:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:71:in `run'
     # /Users/myron/code/rspec-dev/repos/rspec-core/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/myron/code/rspec-dev/repos/rspec-core/exe/rspec:4:in `<top (required)>'
     # ./bin/rspec:14:in `load'
     # ./bin/rspec:14:in `<main>'
```

Notice:

* When we use `Symbol#to_proc` it results in a `NoMethodError`.
* In the other two cases, it doesn't provide the expression, either. However, if I split them onto multiple lines, it works.

@yujinakayama can we do anything about these cases?  If not, should we back this feature out and release 3.6 without it?

/cc @rspec/rspec
